This notebook reads the Top 1000 movies csv file, transformsand cleans the data, and spits out a JSON file

In [18]:
# Import dependencies
import pandas as pd
import csv
import json
import os
import ast
import warnings
warnings.filterwarnings('ignore')

In [19]:
# Read CSV
df = pd.read_csv('imdb_top_1000_movies_final.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/imdb_top_1000_movies_final.csv'

In [14]:
# Show CSV
df.head()

,Title,Year,Rating,Director,Stars,Votes,Genres
0,The Shawshank Redemption,1994,9.3,Frank Darabont,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will...",2717298,[Drama]
1,The Godfather,1972,9.2,Francis Ford Coppola,"[Marlon Brando, Al Pacino, James Caan, Diane K...",1887987,"[Crime, Drama]"
2,The Dark Knight,2008,9.0,Christopher Nolan,"[Christian Bale, Heath Ledger, Aaron Eckhart, ...",2689938,"[Action, Crime, Drama]"
3,The Lord of the Rings: The Return of the King,2003,9.0,Peter Jackson,"[Elijah Wood, Viggo Mortensen, Ian McKellen, O...",1869736,"[Action, Adventure, Drama]"
4,Schindler's List,1993,9.0,Steven Spielberg,"[Liam Neeson, Ralph Fiennes, Ben Kingsley, Car...",1372578,"[Biography, Drama, History]"

In [15]:
# Convert the string representation of the list to an actual list
df['Stars'] = df['Stars'].apply(lambda x: ast.literal_eval(x))
df['Genres'] = df['Genres'].apply(lambda x: ast.literal_eval(x))

ValueError: malformed node or string: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler']

In [5]:
# Clean up the 'Year' column by removing parentheses and Roman numerals I, II, and III
df['Year'] = df['Year'].str.replace('(', '').str.replace(')', '').str.replace('I', '').str.replace('II', '').str.replace('III', '')

/Users/meganconnelly/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

In [6]:
# Show the dataframe
df

,Title,Year,Rating,Director,Stars,Votes,Gross,Genres
0,The Shawshank Redemption,1994,9.3,Frank Darabont,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will...",2717298,#1,[Drama]
1,The Godfather,1972,9.2,Francis Ford Coppola,"[Marlon Brando, Al Pacino, James Caan, Diane K...",1887987,#2,"[Crime, Drama]"
2,The Dark Knight,2008,9.0,Christopher Nolan,"[Christian Bale, Heath Ledger, Aaron Eckhart, ...",2689938,#3,"[Action, Crime, Drama]"
3,The Lord of the Rings: The Return of the King,2003,9.0,Peter Jackson,"[Elijah Wood, Viggo Mortensen, Ian McKellen, O...",1869736,#7,"[Action, Adventure, Drama]"
4,Schindler's List,1993,9.0,Steven Spielberg,"[Liam Neeson, Ralph Fiennes, Ben Kingsley, Car...",1372578,#6,"[Biography, Drama, History]"
...,...,...,...,...,...,...,...,...
995,Shine,1996,7.6,Scott Hicks,"[Geoffrey Rush, Armin Mueller-Stahl, Justin Br...",55041,35810000,"[Biography, Drama, Music]"
996,Eyes Without a Face,1960,7.6,Georges Franju,"[Pierre Brasseur, Alida Valli, Juliette Maynie...",32886,50000,"[Drama, Horror]"
997,The Odd Couple,1968,7.6,Gene Saks,"[Jack Lemmon, Walter Matthau, John Fiedler, He...",35909,44530000,[Comedy]
998,The Invisible Man,1933,7.6,James Whale,"[Claude Rains, Gloria Stuart, William Harrigan...",37048,37048,"[Horror, Sci-Fi]"
999,Celda 211,2009,7.6,Daniel Monzón,"[Luis Tosar, Alberto Ammann, Antonio Resines, ...",68803,68803,"[Action, Adventure, Crime]"

In [7]:
# Drop the 'Gross' column
df = df.drop('Gross', axis=1)

In [8]:
# Show the dataframe
df

,Title,Year,Rating,Director,Stars,Votes,Genres
0,The Shawshank Redemption,1994,9.3,Frank Darabont,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will...",2717298,[Drama]
1,The Godfather,1972,9.2,Francis Ford Coppola,"[Marlon Brando, Al Pacino, James Caan, Diane K...",1887987,"[Crime, Drama]"
2,The Dark Knight,2008,9.0,Christopher Nolan,"[Christian Bale, Heath Ledger, Aaron Eckhart, ...",2689938,"[Action, Crime, Drama]"
3,The Lord of the Rings: The Return of the King,2003,9.0,Peter Jackson,"[Elijah Wood, Viggo Mortensen, Ian McKellen, O...",1869736,"[Action, Adventure, Drama]"
4,Schindler's List,1993,9.0,Steven Spielberg,"[Liam Neeson, Ralph Fiennes, Ben Kingsley, Car...",1372578,"[Biography, Drama, History]"
...,...,...,...,...,...,...,...
995,Shine,1996,7.6,Scott Hicks,"[Geoffrey Rush, Armin Mueller-Stahl, Justin Br...",55041,"[Biography, Drama, Music]"
996,Eyes Without a Face,1960,7.6,Georges Franju,"[Pierre Brasseur, Alida Valli, Juliette Maynie...",32886,"[Drama, Horror]"
997,The Odd Couple,1968,7.6,Gene Saks,"[Jack Lemmon, Walter Matthau, John Fiedler, He...",35909,[Comedy]
998,The Invisible Man,1933,7.6,James Whale,"[Claude Rains, Gloria Stuart, William Harrigan...",37048,"[Horror, Sci-Fi]"
999,Celda 211,2009,7.6,Daniel Monzón,"[Luis Tosar, Alberto Ammann, Antonio Resines, ...",68803,"[Action, Adventure, Crime]"

In [9]:
# Export dataframe to JSON file
df.to_json('imdb_top_1000_movies.json', orient='records')